### ISSUE TITLE
Implementar atalho para Mesclar

### ISSUE THREAD

**Issue by AndreaInfUFSM** [examclipper/examclipper#15]
Selecionar e mesclar são operações muito comuns que podem ser feitas rapidamente usando mouse + teclado. Implementar tecla de atalho para Mesclar próxima da mão esquerda (usuário destro seleciona com mouse na mão direita e tecla atalho com mão esquerda).

**Comment by marlonleoner** [comment]
@AndreaInfUFSM Seria melhor a utilização de duas teclas ou apenas uma?

**Comment by AndreaInfUFSM** [comment]
Uma tecla me parece melhor

**Comment by AndreaInfUFSM** [comment]
Faça um teste numa página com grupos de regiões a serem mescladas
